# array_horizontal_layout_threshold = 0
array_layout                        = "Visual"
array_width                         = 0
chain_indent                        = "Visual"
chain_one_line_max                  = 1
chain_split_single_child            = true
# closure_block_indent_threshold    = 7
# combine_control_expr              = true
comment_width                       = 120
condense_wildcard_suffixes          = true
control_style                       = "Rfc"
control_brace_style                 = "AlwaysSameLine"
# disable_all_formatting            = false
error_on_line_overflow              = true
fn_args_density                     = "Vertical"
fn_args_layout                      = "Visual"
fn_args_paren_newline               = false
fn_brace_style                      = "AlwaysNextLine"
fn_call_style                       = "Visual"
fn_call_width                       = 0
fn_empty_single_line                = true
fn_return_indent                    = "WithWhereClause"
fn_single_line                      = false
force_explicit_abi                  = true
force_format_strings                = true
format_strings                      = true
generics_indent                     = "Visual"
hard_tabs                           = false
impl_empty_single_line              = true
indent_match_arms                   = true
imports_indent                      = "Visual"
imports_layout                      = "Vertical"
item_brace_style                    = "AlwaysNextLine"
# match_block_trailing_comma        = false 
max_width                           = 120
newline_style                       = "Unix"
normalize_comments                  = true
reorder_imported_names              = true
reorder_imports                     = true
reorder_imports_in_group            = true
single_line_if_else_max_width       = 0
# skip_children                     = false
space_after_bound_colon             = true
struct_field_align_threshold        = 60
space_after_struct_lit_field_colon  = true
space_after_type_annotation_colon   = true
space_before_bound                  = false
space_before_struct_lit_field_colon = false
space_before_type_annotation        = false
spaces_around_ranges                = true
spaces_within_angle_brackets        = false
spaces_within_parens                = false
spaces_within_square_brackets       = false
struct_lit_multiline_style          = "ForceMulti"
struct_lit_style                    = "Visual"
struct_lit_width                    = 0
struct_variant_width                = 0
tab_spaces                          = 4
take_source_hints                   = true
trailing_comma                      = "Vertical"
trailing_semicolon                  = true
type_punctuation_density            = "Wide"
use_try_shorthand                   = true
where_density                       = "Vertical"
where_layout                        = "Vertical"
where_pred_indent                   = "Visual"
where_style                         = "Rfc"
wrap_comments                       = true
wrap_match_arms                     = true
write_mode                          = "Overwrite"