language: rust
cache: cargo
addons:
  apt:
    packages:
    - libssl-dev
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
before_script:
- export PATH="$PATH:$HOME/.cargo/bin"
- which rustfmt || cargo install rustfmt
script:
# Make sure code conforms with rustfmt
- cargo fmt -- --write-mode=diff
# Build the application
- cargo clean
- cargo build
- cargo test
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi